/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        spacecadet: "#1A334F",
        gunmetal: "#182431",
        dark: "#212121",
        crayola: "#A7ADBB",
        antiflash: "#EFF1F4",
        lightgray: "#C7C7C7",
      },
      padding: {
        shorter4: "1vw",
        shorter3: "2vw",
        shorter2: "3vw",
        shorter: "4vw",
        normal: "6vw",
        longer: "8vw",
        longer2: "10vw",
        longer3: "12vw",
        longer4: "14vw",
        longer5: "16vw",
        longer6: "18vw",
        longer7: "20vw",
        longer8: "22vw",
        longer9: "24vw",
        longer10: "26vw",
      },
      margin: {
        shorter4: "1vw",
        shorter3: "2vw",
        shorter2: "3vw",
        shorter: "4vw",
        normal: "6vw",
        longer: "8vw",
        longer2: "10vw",
        longer3: "12vw",
        longer4: "14vw",
        longer5: "16vw",
        longer6: "18vw",
        longer7: "20vw",
        longer8: "22vw",
        longer9: "24vw",
        longer10: "26vw",
      },
      borderWidth: {
        1: "1px",
        3: "3px",
        10: "10px",
        12: "12px",
        14: "14px",
        16: "16px",
        18: "18px",
        20: "20px",
      },
      fontFamily: {
        arial: ["Arial", "sans-serif"],
        argentcf: ["Argent CF", "sans-serif"],
        grandesign: ["Grandesign Neue Roman", "sans-serif"],
      },
      fontSize: {
        "10xl": "10rem",
      },
      boxShadow: {
        xl: "10px -10px 0px 0px rgba(26, 51, 79)",
      },
      inset: {
        18: "4.5rem",
      },
    },
  },
  plugins: [],
};
